#pragma once

/// Umbrella header for Universal AI Inference Runtime (Phase 1).

#include "uaii/version.hpp"
#include "uaii/core/config.hpp"
#include "uaii/core/error.hpp"
#include "uaii/core/log.hpp"
#include "uaii/core/plugin.hpp"
#include "uaii/interfaces/backend.hpp"
#include "uaii/interfaces/loader.hpp"
#include "uaii/interfaces/operator_iface.hpp"
#include "uaii/interfaces/scheduler.hpp"
#include "uaii/interfaces/storage.hpp"
#include "uaii/interfaces/tokenizer.hpp"
#include "uaii/interfaces/types.hpp"
#include "uaii/ir/ir.hpp"
#include "uaii/memory/memory.hpp"
#include "uaii/kernels/kernels.hpp"
#include "uaii/backends/cpu_backend.hpp"
#include "uaii/loaders/loaders.hpp"
#include "uaii/tokenizers/tokenizers.hpp"
#include "uaii/planner/planner.hpp"
#include "uaii/storage/storage.hpp"
#include "uaii/profiler/profiler.hpp"
#include "uaii/quant/quant.hpp"
#include "uaii/runtime/runtime.hpp"
