option(UAII_BUILD_TESTS "Build unit tests" ON)
option(UAII_BUILD_PLUGINS "Build example plugins" ON)
option(UAII_BUILD_PYTHON "Build Python extension module (pybind11)" OFF)
option(UAII_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)

# Phase 5 native backend scaffolds (host-fallback always available without SDKs)
option(UAII_WITH_CUDA "Enable CUDA native device path (cuBLASLt + kernels)" OFF)
option(UAII_WITH_METAL "Enable Metal native device path" OFF)
option(UAII_WITH_VULKAN "Enable Vulkan native device path" OFF)
option(UAII_WITH_WEBGPU "Enable WebGPU native device path" OFF)
option(UAII_WITH_ROCM "Enable ROCm native device path" OFF)
option(UAII_WITH_ONEDNN "Link Intel oneDNN for CPU GEMM" OFF)
option(UAII_WITH_OPENBLAS "Link OpenBLAS for CPU GEMM" OFF)
option(UAII_WITH_LIBTORCH "Enable LibTorch PyTorch loader" OFF)
option(UAII_WITH_SENTENCEPIECE "Link SentencePiece tokenizer" OFF)
option(UAII_WITH_ONNX "Enable ONNX protobuf loader" ON)
