option(UAII_BUILD_TESTS "Build unit tests" ON)
option(UAII_BUILD_PLUGINS "Build example plugins" ON)
option(UAII_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)

# Future backend toggles (Phase 5+)
option(UAII_WITH_CUDA "Enable CUDA backend" OFF)
option(UAII_WITH_METAL "Enable Metal backend" OFF)
option(UAII_WITH_VULKAN "Enable Vulkan backend" OFF)
option(UAII_WITH_WEBGPU "Enable WebGPU backend" OFF)
option(UAII_WITH_ROCM "Enable ROCm backend" OFF)
