option(UAII_BUILD_TESTS "Build unit tests" ON)
option(UAII_BUILD_PLUGINS "Build example plugins" ON)
option(UAII_BUILD_PYTHON "Build Python extension module (pybind11)" OFF)
option(UAII_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)

# Phase 5 native backend scaffolds (host-fallback always available without SDKs)
option(UAII_WITH_CUDA "Enable CUDA native scaffold path" OFF)
option(UAII_WITH_METAL "Enable Metal native scaffold path" OFF)
option(UAII_WITH_VULKAN "Enable Vulkan native scaffold path" OFF)
option(UAII_WITH_WEBGPU "Enable WebGPU native scaffold path" OFF)
option(UAII_WITH_ROCM "Enable ROCm native scaffold path" OFF)
